"""Conservative detection logic for excludable code candidates."""

from typing import Any, Dict, List, Optional


class ConservativeDetector:
    """Conservative detector for excludable code candidates.

    Uses strict criteria to minimize false positives when identifying
    code that should be excluded from coverage metrics.
    """

    # High-confidence generated code patterns
    GENERATED_CODE_PATTERNS = [
        r"AUTO-GENERATED",
        r"DO NOT EDIT",
        r"GENERATED CODE",
        r"This file is generated",
        r"autogenerated",
        r"auto-generated",
        r"generated by",
        r"generated from",
    ]

    # Definite vendor code patterns
    VENDOR_PATTERNS = [
        "vendor/",
        "node_modules/",
        "site-packages/",
        "dist-packages/",
        ".venv/",
        "venv/",
    ]

    # Clear migration markers
    MIGRATION_MARKERS = [
        "DEPRECATED",
        "deprecated",
        "LEGACY",
        "legacy",
    ]

    def __init__(self) -> None:
        """Initialize the conservative detector."""
        pass

    def is_definitely_generated(self, file_content: str) -> bool:
        """Check if file is definitely generated code.

        Uses strict criteria - only returns True if there's strong evidence.

        Args:
            file_content: Content of the file

        Returns:
            True if file is definitely generated
        """
        # Must have explicit generation marker
        for pattern in self.GENERATED_CODE_PATTERNS:
            if pattern.lower() in file_content.lower():
                return True

        return False

    def is_definitely_vendor(self, file_path: str) -> bool:
        """Check if file is definitely vendor code.

        Uses strict criteria - only returns True if in vendor directory.

        Args:
            file_path: Path to the file

        Returns:
            True if file is definitely vendor code
        """
        # Must be in vendor directory
        for pattern in self.VENDOR_PATTERNS:
            if pattern in file_path:
                return True

        return False

    def is_definitely_deprecated(self, file_content: str) -> bool:
        """Check if file is definitely deprecated.

        Uses strict criteria - only returns True if explicitly marked.

        Args:
            file_content: Content of the file

        Returns:
            True if file is definitely deprecated
        """
        # Must have explicit deprecation marker
        for marker in self.MIGRATION_MARKERS:
            if marker in file_content:
                return True

        return False

    def is_unreachable_code(self, file_content: str) -> bool:
        """Check if code is unreachable.

        Uses strict criteria - only returns True for obvious cases.

        Args:
            file_content: Content of the file

        Returns:
            True if code is unreachable
        """
        # Check for obvious unreachable patterns
        unreachable_patterns = [
            "if False:",
            "if false:",
            "if 0:",
            "raise NotImplementedError",
            "raise NotImplemented",
        ]

        for pattern in unreachable_patterns:
            if pattern in file_content:
                return True

        return False

    def has_public_api(self, file_content: str) -> bool:
        """Check if file defines public API.

        Args:
            file_content: Content of the file

        Returns:
            True if file defines public API
        """
        # Check for __all__ definition
        if "__all__" in file_content:
            return True

        # Check for public class definitions
        if "class " in file_content and not file_content.strip().startswith("class _"):
            return True

        # Check for public function definitions
        if "def " in file_content and not file_content.strip().startswith("def _"):
            return True

        return False

    def has_side_effects(self, file_content: str) -> bool:
        """Check if file has side effects.

        Args:
            file_content: Content of the file

        Returns:
            True if file has side effects
        """
        side_effect_patterns = [
            "sys.path",
            "os.environ",
            "monkey patch",
            "global ",
        ]

        for pattern in side_effect_patterns:
            if pattern in file_content:
                return True

        return False

    def is_test_file(self, file_path: str) -> bool:
        """Check if file is a test file.

        Args:
            file_path: Path to the file

        Returns:
            True if file is a test file
        """
        test_patterns = [
            "/test/",
            "/tests/",
            "_test.py",
            "_spec.py",
            "test_",
            "spec_",
        ]

        for pattern in test_patterns:
            if pattern in file_path:
                return True

        return False

    def is_safe_to_exclude(
        self, file_path: str, file_content: str
    ) -> Dict[str, Any]:
        """Determine if file is safe to exclude from coverage.

        Uses conservative approach - only excludes if certain.

        Args:
            file_path: Path to the file
            file_content: Content of the file

        Returns:
            Dictionary with exclusion decision and reasoning
        """
        reasons = []
        is_safe = False

        # Check if definitely generated
        if self.is_definitely_generated(file_content):
            reasons.append("Definitely generated code")
            is_safe = True

        # Check if definitely vendor
        if self.is_definitely_vendor(file_path):
            reasons.append("Definitely vendor code")
            is_safe = True

        # Check if definitely deprecated
        if self.is_definitely_deprecated(file_content):
            reasons.append("Definitely deprecated code")
            is_safe = True

        # Check if unreachable
        if self.is_unreachable_code(file_content):
            reasons.append("Unreachable code")
            is_safe = True

        # Check for disqualifying factors
        disqualifiers = []

        if self.has_public_api(file_content):
            disqualifiers.append("Defines public API")
            is_safe = False

        if self.has_side_effects(file_content):
            disqualifiers.append("Has side effects")
            is_safe = False

        if self.is_test_file(file_path):
            disqualifiers.append("Is test file")
            is_safe = False

        return {
            "file_path": file_path,
            "is_safe_to_exclude": is_safe,
            "reasons": reasons,
            "disqualifiers": disqualifiers,
            "confidence": 0.95 if is_safe and not disqualifiers else 0.0,
        }

    def filter_candidates(
        self, candidates: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """Filter candidates using conservative criteria.

        Args:
            candidates: List of candidate files

        Returns:
            Filtered list of safe-to-exclude candidates
        """
        safe_candidates = []

        for candidate in candidates:
            file_path = candidate.get("file_path", "")
            file_content = candidate.get("content", "")

            safety_check = self.is_safe_to_exclude(file_path, file_content)

            if safety_check["is_safe_to_exclude"]:
                candidate["safety_check"] = safety_check
                safe_candidates.append(candidate)

        return safe_candidates

    def get_exclusion_recommendation(
        self, file_path: str, file_content: str
    ) -> Dict[str, Any]:
        """Get exclusion recommendation for a file.

        Args:
            file_path: Path to the file
            file_content: Content of the file

        Returns:
            Recommendation with confidence and reasoning
        """
        safety_check = self.is_safe_to_exclude(file_path, file_content)

        recommendation = {
            "file_path": file_path,
            "action": "EXCLUDE" if safety_check["is_safe_to_exclude"] else "INCLUDE",
            "confidence": safety_check["confidence"],
            "reasons": safety_check["reasons"],
            "disqualifiers": safety_check["disqualifiers"],
        }

        if safety_check["is_safe_to_exclude"]:
            recommendation["message"] = f"Safe to exclude: {', '.join(safety_check['reasons'])}"
        else:
            if safety_check["disqualifiers"]:
                recommendation["message"] = f"Cannot exclude: {', '.join(safety_check['disqualifiers'])}"
            else:
                recommendation["message"] = "Insufficient evidence to exclude"

        return recommendation
