"""Service for detecting excludable code candidates."""

from typing import Any, Dict, List, Optional


class ExcludableCodeCandidateService:
    """Service for detecting code that should be excluded from coverage.

    Identifies candidates for exclusion:
    - Generated code
    - Vendor code
    - Migration paths
    - Zero-hit signals
    """

    def __init__(self) -> None:
        """Initialize the excludable code service."""
        pass

    def detect_generated_code(
        self, file_path: str, file_content: str
    ) -> Dict[str, Any]:
        """Detect if code is generated.

        Args:
            file_path: Path to the file
            file_content: Content of the file

        Returns:
            Detection result with confidence score
        """
        indicators = []
        confidence = 0.0

        # Check for common generated code markers
        generated_markers = [
            "AUTO-GENERATED",
            "DO NOT EDIT",
            "GENERATED CODE",
            "This file is generated",
            "autogenerated",
            "auto-generated",
        ]

        for marker in generated_markers:
            if marker.lower() in file_content.lower():
                indicators.append(f"Found marker: {marker}")
                confidence += 0.3

        # Check file extensions
        generated_extensions = [".pb.py", ".pb2.py", ".pb2_grpc.py", ".g.dart"]
        for ext in generated_extensions:
            if file_path.endswith(ext):
                indicators.append(f"Generated file extension: {ext}")
                confidence += 0.4

        # Check for code generation patterns
        generation_patterns = [
            "generated by",
            "generated from",
            "generated with",
            "code generator",
        ]

        for pattern in generation_patterns:
            if pattern.lower() in file_content.lower():
                indicators.append(f"Found generation pattern: {pattern}")
                confidence += 0.2

        # Cap confidence at 1.0
        confidence = min(confidence, 1.0)

        return {
            "is_generated": confidence > 0.5,
            "confidence": confidence,
            "indicators": indicators,
        }

    def detect_vendor_code(self, file_path: str) -> Dict[str, Any]:
        """Detect if code is vendor/third-party code.

        Args:
            file_path: Path to the file

        Returns:
            Detection result with confidence score
        """
        indicators = []
        confidence = 0.0

        # Check for vendor directories
        vendor_patterns = [
            "vendor/",
            "node_modules/",
            ".venv/",
            "venv/",
            "site-packages/",
            "dist-packages/",
            "third_party/",
            "external/",
        ]

        for pattern in vendor_patterns:
            if pattern in file_path:
                indicators.append(f"Found vendor pattern: {pattern}")
                confidence += 0.4

        # Check for common vendor files
        vendor_files = [
            "jquery.js",
            "bootstrap.js",
            "react.js",
            "angular.js",
            "lodash.js",
        ]

        for vendor_file in vendor_files:
            if vendor_file in file_path:
                indicators.append(f"Found vendor file: {vendor_file}")
                confidence += 0.5

        # Cap confidence at 1.0
        confidence = min(confidence, 1.0)

        return {
            "is_vendor": confidence > 0.5,
            "confidence": confidence,
            "indicators": indicators,
        }

    def detect_migration_path(
        self, file_path: str, file_content: str
    ) -> Dict[str, Any]:
        """Detect if code is part of a migration path.

        Args:
            file_path: Path to the file
            file_content: Content of the file

        Returns:
            Detection result with confidence score
        """
        indicators = []
        confidence = 0.0

        # Check for migration markers
        migration_markers = [
            "DEPRECATED",
            "deprecated",
            "MIGRATION",
            "migration",
            "LEGACY",
            "legacy",
            "TODO: remove",
            "TODO: delete",
            "scheduled for removal",
        ]

        for marker in migration_markers:
            if marker in file_content:
                indicators.append(f"Found migration marker: {marker}")
                confidence += 0.25

        # Check for migration-related comments
        migration_comments = [
            "will be removed",
            "to be removed",
            "old implementation",
            "temporary",
            "temporary fix",
        ]

        for comment in migration_comments:
            if comment.lower() in file_content.lower():
                indicators.append(f"Found migration comment: {comment}")
                confidence += 0.2

        # Check for version-specific code
        if "v1" in file_path or "v2" in file_path:
            indicators.append("Found version-specific path")
            confidence += 0.15

        # Cap confidence at 1.0
        confidence = min(confidence, 1.0)

        return {
            "is_migration": confidence > 0.5,
            "confidence": confidence,
            "indicators": indicators,
        }

    def analyze_zero_hit_signals(
        self, file_path: str, coverage_data: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Analyze zero-hit signals in coverage data.

        Args:
            file_path: Path to the file
            coverage_data: Coverage data for the file

        Returns:
            Analysis result with signals
        """
        signals = []
        confidence = 0.0

        # Check if file has zero hits
        hits = coverage_data.get("hits", 0)
        if hits == 0:
            signals.append("File has zero hits")
            confidence += 0.3

        # Check if all lines are uncovered
        total_lines = coverage_data.get("total_lines", 0)
        covered_lines = coverage_data.get("covered_lines", 0)

        if total_lines > 0 and covered_lines == 0:
            signals.append("All lines are uncovered")
            confidence += 0.3

        # Check for unreachable code patterns
        if "if False:" in coverage_data.get("content", ""):
            signals.append("Found unreachable code pattern")
            confidence += 0.4

        if "raise NotImplementedError" in coverage_data.get("content", ""):
            signals.append("Found not-implemented code")
            confidence += 0.2

        # Check for test-only code
        if "test" in file_path.lower() or "spec" in file_path.lower():
            signals.append("File appears to be test code")
            confidence += 0.1

        # Cap confidence at 1.0
        confidence = min(confidence, 1.0)

        return {
            "has_zero_hit_signals": confidence > 0.5,
            "confidence": confidence,
            "signals": signals,
        }

    def score_excludability(
        self,
        file_path: str,
        file_content: str,
        coverage_data: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Score how excludable a file is.

        Args:
            file_path: Path to the file
            file_content: Content of the file
            coverage_data: Coverage data for the file

        Returns:
            Excludability score with breakdown
        """
        # Analyze all signals
        generated = self.detect_generated_code(file_path, file_content)
        vendor = self.detect_vendor_code(file_path)
        migration = self.detect_migration_path(file_path, file_content)
        zero_hit = self.analyze_zero_hit_signals(file_path, coverage_data)

        # Calculate overall score (weighted average)
        scores = [
            generated["confidence"] * 0.4,  # Generated code is strongest signal
            vendor["confidence"] * 0.3,  # Vendor code is strong signal
            migration["confidence"] * 0.2,  # Migration code is moderate signal
            zero_hit["confidence"] * 0.1,  # Zero-hit is weak signal
        ]

        overall_score = sum(scores)

        return {
            "file_path": file_path,
            "excludability_score": overall_score,
            "should_exclude": overall_score > 0.5,
            "confidence": overall_score,
            "breakdown": {
                "generated": generated,
                "vendor": vendor,
                "migration": migration,
                "zero_hit": zero_hit,
            },
        }

    def find_excludable_candidates(
        self,
        files: List[Dict[str, Any]],
        min_confidence: float = 0.5,
    ) -> List[Dict[str, Any]]:
        """Find candidates for exclusion from coverage.

        Args:
            files: List of files with path, content, and coverage data
            min_confidence: Minimum confidence threshold

        Returns:
            List of excludable candidates ranked by confidence
        """
        candidates = []

        for file_info in files:
            file_path = file_info.get("path", "")
            file_content = file_info.get("content", "")
            coverage_data = file_info.get("coverage", {})

            score_result = self.score_excludability(
                file_path, file_content, coverage_data
            )

            if score_result["excludability_score"] >= min_confidence:
                candidates.append(score_result)

        # Sort by excludability score (descending)
        candidates.sort(key=lambda x: x["excludability_score"], reverse=True)

        return candidates

    def validate_candidate(
        self, file_path: str, file_content: str
    ) -> Dict[str, Any]:
        """Validate that a candidate is safe to exclude.

        Args:
            file_path: Path to the file
            file_content: Content of the file

        Returns:
            Validation result with warnings
        """
        warnings = []
        is_safe = True

        # Check if file is imported by other files
        if "import" in file_content and "from" in file_content:
            warnings.append("File contains imports - may be a dependency")
            is_safe = False

        # Check if file exports public API
        if "__all__" in file_content:
            warnings.append("File defines public API - may be important")
            is_safe = False

        # Check if file has side effects
        side_effect_patterns = [
            "global ",
            "sys.path",
            "os.environ",
            "monkey patch",
        ]

        for pattern in side_effect_patterns:
            if pattern in file_content:
                warnings.append(f"File may have side effects: {pattern}")
                is_safe = False

        return {
            "file_path": file_path,
            "is_safe_to_exclude": is_safe,
            "warnings": warnings,
        }
